Python Review

In [1]:
a = 2.0

# Use hashtag for comments
# Unlike MATLAB, you have to print anything you want to see:
print(a)

# Data types
a = 1      #int
b = 1.0    #float
c = 'one'  #string

# You can typecast one data type as another
d = int(2.0)
print(d)

# Operations
# + - / * work normally
# // gives floor of a division, ie without remainder
# % gives the remainder of division, modular
# ** gives exponentiation

# Booleans (Bools)
a = 7>9
print(a)
# Bools automatically assume 0 or 1 when combined with ints or floats
print(a*3)
# Connectives and, or, not, can be used
print(((3<6) and (not 8+4==11)))


# Data structures
my_list = [1, 2.0, "seven"]
my_tuple = (1, 2.0, "seven")
my_dict = {'Cat':'Chat', 'Dog':'Chien', 'Sun':'Sol'}

# Call different elements of a collection with square brackets [], indexing starting at 0
print(my_list[1])

# Get the value/entry associated with a key (label) in a dictionary, by calling the key name
print(my_dict['Dog'])


# Loops
# If loop executes indented code below it if the boolean value is true. Need a colon to indent
# Use elif to set out other cases, and else to treat remaining cases
i = 5
if i > 0:
    print(i)
elif i == 5:
    print("doo")
else:
    print("i <= 0")



# While loop keeps executing the indented code repeatedly until a bool turns false
n = 1
while n < 10:
    print(n, end=", ")
    n += 1     # increment n


print("\n")   # print new line

# For loops execute the block of indented code for each element of a specified collection
foo = [1,3,7]
for f in foo:
    print(f)

# Range runs from 0 to the argument-1, only used in for statements
bar = range(8)
for b in bar:
    print(b)

# Range can get second argument for starting value
a = range(2,7)
for y in a:
    print(y)



2.0
2
False
0
True
2.0
Chien
5
1, 2, 3, 4, 5, 6, 7, 8, 9, 

1
3
7
0
1
2
3
4
5
6
7
2
3
4
5
6


In [35]:
# Break will exit the immediate loop 
for i in range(7):
    if i == 5:
        break
    print(i)

print("\n")

# Continue will skip the current iteration in the loop
for i in range(7):
    if i == 5:
        continue
    print(i)  

0
1
2
3
4


0
1
2
3
4
6


In [2]:
# Define a function using def keyword
def my_sum(a: float, b: float):
    ''' Function description turns up when you hover over function call on vscode
    '''
    c = a + b  # Interior variables within scope of function
    return c

# Call the function and pass a parameter for each needed

d = my_sum(3,6)
print(d)

# Can have a function with optional arguments
def my_product(a,b=3):
    c = a*b
    return c

my_product(4)



9


12

In [2]:
# We can call upon modules, which are other .py files containing variables and functions

# First import the relevant module by its file name
import mymodule

# Then call on a specific function by adding .functionname to the package name
print(mymodule.mymodulefunction(3,5))

# There are existing packages, which are collections of modules, such as numpy
import numpy
print(numpy.pi)  # Access the pi variable from numpy package

# Shorten the name of a package you want to repeatedly use
import mymodule as md 

print(md.mymodulevariable)



15
3.141592653589793
2.7


In [22]:
# numpy allows you to store vectors and matrices as arrays, a new data structure
import numpy as np

u = np.array([3, 4, 5]) # Make 1D array, a vector

foo = [1, 2, 3]
v = np.array(foo)  # Convert a list to an array
print(v)

# Do linalg with it
w = np.dot(v,u)
print(w)

M = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(M)

# Multiply vectors and matrices with '@'
print(M@np.transpose(v))

print(u-v)

print(np.eye(3))

print(np.ones([2, 2]))

# linspace(start, stop, num. of elements)
print(np.linspace(2,3,5))

# np functions can operate element wise on arrays
bill = np.array([3,1,2])
print(np.sin(bill))


[1 2 3]
26
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[14 32 50]
[2 2 2]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 1.]
 [1. 1.]]
[2.   2.25 2.5  2.75 3.  ]
[0.14112001 0.84147098 0.90929743]


In [35]:
# Numpy's linalg module can do specific things
A = np.array([ [1, 2, 3],[4, 1, 2],[5, 6, 2]])
b = np.array([2,6,3])

# Solve Ax=b
x = np.linalg.solve(A,b)
print(x)

# Work out det, inv, eig
print(np.linalg.det(A))

print(np.linalg.inv(A))

[eigvals, eigvecs] = np.linalg.eig(A)
print(eigvecs)

[ 1.31372549 -0.8627451   0.80392157]
50.99999999999997
[[-0.19607843  0.2745098   0.01960784]
 [ 0.03921569 -0.25490196  0.19607843]
 [ 0.37254902  0.07843137 -0.1372549 ]]
[[ 0.44053575+0.j          0.34073633+0.44184424j  0.34073633-0.44184424j]
 [ 0.45181944+0.j          0.16370926-0.49638347j  0.16370926+0.49638347j]
 [ 0.77574961+0.j         -0.64457362+0.j         -0.64457362-0.j        ]]


In [ ]:
# SciPy does specific scientific functions: solving nonlinear equations, optimisation
# integration, linear algebra, sparse linear algebra

# matplotlib works well with numpy